-- FUNCIONES PERSONALIZADAS, CINCO EJEMPLOS

DELIMITER //
CREATE FUNCTION CALCULAR_PRECIO_CON_IVA(precio DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
	DECLARE variable DECIMAL(10,2);
	SET variable = precio * 0.19;
	RETURN precio + variable;
END //
DELIMITER ;

DELIMITER //
CREATE FUNCTION OBTENER_TOTAL_PEDIDOS_CLIENTES(id_cliente INT)
RETURNS INT
DETERMINISTIC
BEGIN
	DECLARE consulta INT;
    SET consulta = 
    
END //
DELIMITER ;