USE terminal_transporte;
SELECT * FROM pasajeros; -- SELECT CLASICO DE TODA LA VIDA
SELECT * FROM pasajeros WHERE nombre = 'sophia'; -- SELECT CON CONDICON WHERE QUE BUSCA COINCIDENCIAS
SELECT * FROM pasajeros WHERE nombre = 'sophia' ORDER BY tipoDocumento ASC; -- AQUI LE SOLICITO QUE ME BUSQUE LOS DATOS Y QUE ME LOS ORGANICE DE MANERA ASCENDENTE POR MEDIO DEL TIPO DE DOC.for
SELECT * FROM pasajeros WHERE nombre = 'sophia' ORDER BY tipoDocumento DESC; -- LO MISMO PERO DE MANERA DESCENDENTE
SELECT * FROM  pasajeros WHERE correo LIKE '%@gmail.com'; -- ESTA ES UNA BUSQUEDA POR COINCIDENCIAS ENTRE LAS FILAS USANDO LIKE 
SELECT * FROM  pasajeros WHERE correo LIKE '%@gmail.com' OR correo LIKE '%@yahoo.com'; -- LO MISMO PERO USANDO EL OPERADOR LOGICO OR LO MISMO SUCEDERIA CON AND
SELECT * FROM  pasajeros WHERE NOT correo LIKE '%@gmail.com'; -- SELECCION INVERSA AL USAR NEGACION NOT
SELECT MAX(tipoDocumento) FROM pasajeros; -- TRAE LOS DATOS QUE CONTIENEN EL NUMERO MAYOR CON RESPECTO A tipoDocumento
SELECT MIN(tipoDocumento) FROM pasajeros; -- CONTRARIO A LO ANTERIOR TRAE LOS DATOS CON EL NUMERO MENOR
SELECT COUNT(*) FROM pasajeros; -- CUENTA EL TOTAL DE FILAS QUE TIENEN UN VALOR EN EL PARAMETRO QUE LE PASAMOS
SELECT SUM(precio) FROM tiquetes; -- SUMA TODOS LOS VALORES DE LAS FILAS A LOS CUALES PASAMOS POR PARAMETRO
SELECT AVG(precio) FROM tiquetes; -- AROJA EL PROMEDIO DE LAS FILAS QUE PASMOS POR PARAMETRO
SELECT * FROM pasajeros WHERE nombre IN ('SOPHIA', 'JUAN'); -- BUSCA COINCIDENCIA DE PLANO, SIN IMPORTAR EL TIPO DE LETRA
SELECT * FROM pasajeros WHERE numeroDeDocumento BETWEEN 1000000000 AND 2000000000; -- BUSCA POR RANGOS USANDO ESTA SINTAXIS
SELECT nombre AS Nombrecillos, apellidoPaterno AS Apedirijillos FROM pasajeros; -- PERMITE PONERLE OTROS NOMBRES A LAS COLUMNAS QUE ESTAMOS CONSULTANDO
SELECT CONCAT(nombre, ' ', apellidoPaterno, ' ', apellidoMaterno) AS Nombre_Completo FROM pasajeros; -- CONMCAT PERMITE CONCATENAR INFORMACION DE DISTINTAS COLUMNAS EN UNA SOLA
SELECT COUNT(tipoDocumento), tipoDocumento FROM pasajeros GROUP BY tipoDocumento; -- SE LE SOLICITA QUE ORGANICE POR GRUPO BASANDOSE EN EL CONTEO QUE HIZO DE LOS TIPOS DE DOCUMENTOS


